### ISSUE TITLE
Filesystem used on HDD by stock firmware?

### ISSUE THREAD

**Issue by pfalcon** [ubis/HI3536DV100#5]
Some great work in this project, thanks for sharing!

From README:

> I have configured to record on motion, however, I noticed that motion detection doesn't always work and I had to switch to 24/7 recording.

Oh, you're the lucky one :-). I know that many people (including me) complain that motion detection vice-versa gives many false positives, so recordings aren't that useful.

> I would like to save records 24/7 to my NAS, however, stock sofware (Sofia) allows records to upload only via FTP server and when motion is detected. There is no option for continous record uploading. I haven't figured out what i'm gonna do about it.

Ok, so what's the problem with doing that? Let me start with the question - which filesystem is used on the HDD where video files stored? For as long as it's filesystem (and not kewl hacks like using raw device ;-) ), next step would be: 1) allow to store executables on the HDD; 2) make those executables be run on th edevice boot (in parallel with `Sofia`). That would require firmware modification, but you started with that. So, I really wonder why it seems like everyone follows 2 extreme approaches: a) try to build the whole system from scratch, or; b) give up and use the stock fw as is - instead of looking for ways how to "sideload" custom software on the stock fw.

**Comment by ubis** [comment]
Hi @pfalcon 

Indeed I get many false positives, however what is worst, that sometimes motion is not detected at all thus no recording saved in my NAS. Perhaps I should set sensitivity to max, though this will lead to more false positives.

> which filesystem is used on the HDD where video files stored?

HDD is not mounted on Linux, it is formatted, mounted & used only by `Sofia` application. There are no partitions.

```
brw-------    1    8,   0 sda
lrwxrwxrwx    1         3 SataHub0 -> sda
lrwxrwxrwx    1         3 hhd1 -> sda
```
For now, I cannot tell the exact filesystem on the HDD because there is no built `hexdump` utility in NVR's busybox. I will try to extract some header bytes from HDD and check it with my machine. Perhaps it does not even use a FS, it might be using raw device and I am 90% that this is the case.

You cannot just mount twice the same HDD - on `Sofia` and on Linux.

`Sofia` has many built-in things. For example, if you would look up into `cmdline`:

```
~ # cat /proc/cmdline
mem=83M console=ttyAMA0,115200 root=/dev/mtdblock1 rootfstype=squashfs mtdparts=hi_sfc:320K(boot),3968K(romfs),7040K(usr),1600K(web),2816K(custom),128K(logo),512K(mtd) coherent_pool=2M
```

NVR has 128MB RAM, however, it boots with 83MB for some reason. After `Sofia` is launched - there are checks for `mem=83M` in `cmdline`. If `mem` in `cmdline` is higher than 83MB (or no `mem` entry at all) then `Sofia` will reboot the NVR instantly. It is something related with video subsystem/hdmi/dsub output, I have not investigated this.

> So, I really wonder why it seems like everyone follows 2 extreme approaches: a) try to build the whole system from scratch

Well, most of the time it is faster and easier just to build everything from scratch. However, the only reason I have not wiped everything and build from scratch is camera configuration.

As of now, I am thinking to install `ffmpeg` on the NVR and stream it directly to FTP server(server details should be somewhere in Config partition). That FTP server is hosted on the `middle` server, which provides isolation for cameras and access from my home network.

**Comment by pfalcon** [comment]
Thanks for the detailed response!

> Perhaps it does not even use a FS, it might be using raw device and I am 90% that this is the case.

As I mentioned above, I keep such an option in mind, but that would be indeed the hardest case, if it has a custom userland-level filesystem or accesses HDD as a raw block device.

> You cannot just mount twice the same HDD - on Sofia and on Linux.

Right, but filesystems are mounted on the OS (Linux) level, even if by application request. Can you please double-check that? Is there `mount` command? If not, you get effectively the same info using `cat /proc/mounts`. Regardless of the outcome, can you please also share output of `cat /proc/filesystems`, because if not HDD, then we can put something on a USB drive. Btw, maybe you could add such dumps to this repository, along /proc/mtd, etc. dumps you already have. (And to elaborate, I own a similar device, but I'm not sure even which chip it has, and it's elsewhere where I won't have access to it anytime soon. I consider getting another device purely for experimenting.) 

> however, it boots with 83MB for some reason. [...] It is something related with video subsystem/hdmi/dsub output, I have not investigated this.

Yeah, I bet that's it - the rest of memory is used as "VRAM" by "GPU" on the chip.

> Well, most of the time it is faster and easier just to build everything from scratch. However, the only reason I have not wiped everything and build from scratch is camera configuration.

I'm sure you're aware of https://github.com/OpenIPC/ , where guys are trying to build completely open-source firmware for Hisilicon (etc.) devices, though as far as I can tell, they concentrate on cameras, not NVRs. And dunno, but for me, the value of these off-the-shelf NVRs comes from the fact that they have know-working baseline system. Which however lacks many smaller features and has pretty bad UI/UX, so what I'd be interested in is to have ability to (easily) have access to the recordings/run additional scripts right on the device.

If you're ok with "from scratch" route, then it's worth to reconsider how helpful these proprietary NVR boxes are at all, with the need to reverse-engineer them. What's needed for an NVR beyond standard "receive network stream and write it to disk" functionality is: a) hardware H.264/H.265 decoding; b) hardware scaling. Just decode a frame, scale it down to reasonable size, and then can perform motion detection on CPU by whatever algorithm you like. The first candidate for that is RasPi4, which should have enough networking/USB3/decoding capabilities for a few cameras. But from software integration PoV, maybe even easier to use x86 box with Intel integrated graphics, with HW decoding using VA-API.

It's just I didn't see a project which tries to efficiently implement the NVR baseline functionality, most things out there are just highlevel toys/prototypes which use OpenCV to demonstrate some "AI", without caring for efficiency or basic functionality (like pre-recording).

**Comment by ubis** [comment]
Turns out `WFS0.4` is used, a quick search shown that it is fairly common on NVR/DVR devices.

I just noticed that I have not posted output of `mount` command in repo, so here it is:

```
~ # mount
/dev/root on / type squashfs (ro,relatime)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
tmpfs on /dev type tmpfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
/dev/mtdblock2 on /usr type squashfs (ro,relatime)
/dev/mtdblock3 on /mnt/web type squashfs (ro,relatime)
/dev/mtdblock4 on /mnt/custom type squashfs (ro,relatime)
/dev/mtdblock5 on /mnt/logo type cramfs (ro,relatime)
/dev/mtdblock6 on /mnt/mtd type jffs2 (rw,relatime)
/dev/mem on /var type ramfs (rw,relatime)
none on /mnt/usb type ramfs (rw,relatime,codepage=936,iocharset=gb2312,usefree)
```

And filesystems too:
```
~ # cat /proc/filesystems 
nodev   sysfs
nodev   rootfs
nodev   ramfs
nodev   bdev
nodev   proc
nodev   cgroup
nodev   cgroup2
nodev   tmpfs
nodev   sockfs
nodev   pipefs
nodev   rpc_pipefs
nodev   devpts
        ext3
        ext4
        ext2
        cramfs
        squashfs
        vfat
        msdos
        iso9660
nodev   nfs
nodev   nfs4
        ntfs
nodev   jffs2
        fuseblk
nodev   fuse
nodev   fusectl
nodev   ubifs
```

> I'm sure you're aware of https://github.com/OpenIPC/

Yes. Well, actually I talked with ZigFisher, they have EN/RU Telegram chats, though RU channel is more active - I suppose that is because more RU users are using cameras with Hisilicon CPUs.

> Which however lacks many smaller features and has pretty bad UI/UX, so what I'd be interested in is to have ability to (easily) have access to the recordings/run additional scripts right on the device.

Yeah, exactly. Now my "middle" server (which is between NVR and my home network) does some stuff - cleans up old recordings from NAS monthly and so on.

> If you're ok with "from scratch" route, then it's worth to reconsider how helpful these proprietary NVR boxes are at all, with the need to reverse-engineer them.

Reverse-engineering takes some time and essentially, you are working on a single device which will be used only by you and if HW dies, then probably you would not be able to get the same HW after couple of years. It would not be a problem for me if all kernel drivers were open-source - I do work with OpenWrt/embedded stuff/network routers, there is my OpenWrt 18.06 port working on this SoC. However, now I have chosen just to keep it in tact and use with middle server, because stock NVR software allows configuration for each camera. Those are configured via proprietary protocol(called Sofia protocol, or DVRIP). I have seen some implementations in Python, however, not everything is implemented in these.

> It's just I didn't see a project which tries to efficiently implement the NVR baseline functionality

Yup, unless there is, but it costs a lot.

**Comment by pfalcon** [comment]
> Turns out WFS0.4 is used, a quick search shown that it is fairly common on NVR/DVR devices.

Thanks, never heard about it, read up on it now, good hint!

> And filesystems too:

Thanks for adding those to the repo, and as ext2 and friends are there, seems like path of hosting custom binaries on a USB stick is feasible.

> Yes. Well, actually I talked with ZigFisher, they have EN/RU Telegram chats,

Good to know you guys are aware of each other's projects! I know there's a lot of things in OpenIPC projects, but sometimes it's easier to look into a dedicated thing ;-). It was easy to find your project by the chip name, and thanks for answering questions!

> Reverse-engineering takes some time and essentially, you are working on a single device which will be used only by you and if HW dies, then probably you would not be able to get the same HW after couple of years.

Yeah, I've been doing device hacking for many years, and know how hard it is to "rebuild" it (mostly software side) "from scratch". That's why I'm more interested in "modify existing per your needs approach". And of course, different parties should share info/results so there was overall progress (like OpenWRT demonstrates). So, thanks again for this project and updates to it, I got my answers now, closing. Other folks hopefully will be able to find it using search.

**Comment by pfalcon** [comment]
> sometimes motion is not detected at all thus no recording saved in my NAS

@ubis, Sorry to bother you again, have a question regarding the issue quoted above. Do you have a "pre-recording" setting for motion detection in your firmware?

Because I received my "for experiments" board, and in its settings, I have only "post-recording" setting. And that's exactly the same problem as with my another NVR elsewhere. Without pre-recording, the NVR is rather useless, as oftentimes the recording doesn't have enough footing/details of the motion (catches only "tail" of the motion).

For reference, the board I got is NBD8016S-ULA-V2 http://www.xiongmaitech.com/en/index.php/product/product-detail/4/110/399 , (which is something with HI3536DV100 I could easily find) and has firmware type "C6380202", which matches one of 2 firmwares available for download from the link above.

**Comment by ubis** [comment]
Hi,

Sorry for late reply. This is what I have on Motion detection settings:
![image](https://user-images.githubusercontent.com/3310376/116558029-b0bd6700-a907-11eb-9ac0-64e59a5d2396.png)

> Without pre-recording, the NVR is rather useless, as oftentimes the recording doesn't have enough footing/details of the motion (catches only "tail" of the motion).

This happens to me too and honestly, I don't bother with detection at all. I set it to record everything 24/7.

**Comment by pfalcon** [comment]
> This is what I have on Motion detection settings:

Thanks, I appreciate the response! Don't see anything related to pre-recording there either.

Anyway, I started to look into what openipc.org project has, though probably it will be a long way ;-).
